
GET http://localhost:4446/
###
POST http://localhost:4446/auth/signup
Content-Type: application/json

{

  "name":"PavanKalyan", 
  "email":"pavankalyan571@gmail.com", 
  "phoneNumber":"7702522568", 
  "gender":"male", 
  "password":"pavan@123"

}

###
POST http://localhost:4446/auth/login
Content-Type: application/json

{

  "email":"pavankalyan571@gmail.com",
  "password":"pavan@123"

}

###
GET http://localhost:4446/auth/user-profile
###
GET http://localhost:4446/auth/greeting